### ISSUE TITLE
How to fetch Album Art cover through mqtt?

### ISSUE THREAD

**Issue by ThunderBirrddd** [JohannVR/JohannVRs-Home-Assistant-Addons#7]
Hey, 
First of all thank you so much for this awesome add-on works flawlessly totally in love with this so recently tried mqtt aswell but was wondering how do I get the album cover? i have album cover set to yes under config but after that what to do with it how do I fetch it to my dashboard? 

Help will be really appreciated,
Thankyou.

**Comment by JohannVR** [comment]
Hey, glad to hear you like it! You can get the cover art into HA by adding this to your config:

```
mqtt:
  - image:
      name: "Airplay2 Cover Art"
      image_topic: "airplay2/cover"
      content_type: image/jpeg
```
